{
 "title": "Lambda Guest Agent",
 "time": { "from": "2024-12-05T01:56:17.212Z", "to": "2024-12-05T03:14:10.353Z" },
 "templating": {
  "list": [
   { "name": "host", "query": { "query": "label_values(host)" } },
   {
    "name": "disk",
    "query": {
     "query": "label_values(lambda_guest_agent_diskio_read_bytes,name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "NFS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "NFS Retransmits",
     "type": "timeseries",
     "description": "Retransmits indicate an error with communicating with the NFS server.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "lambda_guest_agent_nfsstat_retrans{host=~\"$host\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "NFS Round Trip Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(lambda_guest_agent_nfsstat_rtt{host=~\"$host\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "NFS Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "max by(host, mountpoint) (rate(lambda_guest_agent_nfsstat_bytes{host=~\"$host\", operation=\"READ\"}[$__rate_interval])) * 8",
       "legendFormat": "__auto"
      },
      {
       "expr": "max by(host, mountpoint) (rate(lambda_guest_agent_nfsstat_bytes{host=~\"$host\", operation=\"WRITE\"}[$__rate_interval])) * -8",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "NFS Average Round Trip Time Per Operation",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by(operation, ) (lambda_guest_agent_nfsstat_rtt_per_op{host=~\"$host\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Local Disk Read/Write",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(lambda_guest_agent_diskio_read_bytes{name=~\"$disk\", host=~\"$host\"}[$__rate_interval])",
       "legendFormat": "__auto"
      },
      {
       "expr": "rate(lambda_guest_agent_diskio_write_bytes{name=~\"$disk\", host=~\"$host\"}[$__rate_interval]) * -1",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Local Disk Utilization Percent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by(host, path) (lambda_guest_agent_disk_used_percent{host=~\"$host\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Infiniband Port Rcv Rate (avg by host)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "avg by(host) (rate(lambda_guest_agent_infiniband_port_rcv_data{host=~\"$host\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Infiniband Port Send Rate (avg by host)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "avg by(host) (rate(lambda_guest_agent_infiniband_port_xmit_data{host=~\"$host\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Ethernet Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "avg by(interface, host) (rate(lambda_guest_agent_net_bytes_recv{host=~\"$host\"}[$__rate_interval])) * 8",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by(host, interface) (rate(lambda_guest_agent_net_bytes_sent{host=~\"$host\"}[$__rate_interval])) * -8",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Utilization (average by host)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by(host) (avg_over_time(lambda_guest_agent_nvidia_smi_utilization_gpu{host=~\"$host\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPU Utilization (average by host)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "targets": [
      {
       "expr": "avg by(host) (avg_over_time(lambda_guest_agent_nvidia_smi_utilization_gpu{host=~\"$host\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPU Power Draw (average by host)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "avg by(host) (avg_over_time(lambda_guest_agent_nvidia_smi_power_draw{host=~\"$host\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPU Power Draw (average by host)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
     "targets": [
      {
       "expr": "avg by(host) (avg_over_time(lambda_guest_agent_nvidia_smi_power_draw{host=~\"$host\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Remapped Rows Uncorrectable",
     "type": "table",
     "description": "Uncorrectable row remaps indicate a fatal ECC memory event within a particular row of GPU memory. Any GPU workload that was mapped to this particular row of memory likely encountered a fatal error.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "targets": [
      {
       "expr": "lambda_guest_agent_nvidia_smi_remapped_rows_uncorrectable > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Remapped Rows Correctable",
     "type": "table",
     "description": "Correctable row remaps indicate a non-fatal ECC memory event within a particular row of GPU memory. The device was able to successfully remap the row out of usage without impact to running workloads.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "targets": [
      {
       "expr": "lambda_guest_agent_nvidia_smi_remapped_rows_correctable > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Remapped Rows Uncorrectable (graph)",
     "type": "timeseries",
     "description": "Use this graph to determine when uncorrectable row remaps occurred. ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
     "targets": [
      {
       "expr": "max by(host, index) (lambda_guest_agent_nvidia_smi_remapped_rows_uncorrectable > 0)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by(host) (avg_over_time(lambda_guest_agent_cpu_usage_user{host=~\"$host\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "targets": [
      {
       "expr": "avg by(host) (avg_over_time(lambda_guest_agent_cpu_usage_user{host=~\"$host\"}[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Timekeeping",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Chrony Frequency",
     "type": "timeseries",
     "description": "The \"frequency\" is the rate by which the system’s clock would be wrong if chronyd was not correcting it. It is expressed in ppm (parts per million). For example, a value of 1 ppm would mean that when the system’s clock thinks it has advanced 1 second, it has actually advanced by 1.000001 seconds relative to true time.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "ppm" } },
     "targets": [
      {
       "expr": "avg by(host) (lambda_guest_agent_chrony_frequency{host=~\"$host\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Chrony Last Offset",
     "type": "timeseries",
     "description": "This is the estimated local offset on the last clock update. This number tracks how far away the local chrony daemon's estimation of true time is from the remote NTP server.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "abs(avg by(host) (lambda_guest_agent_chrony_last_offset{host=~\"$host\"}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Chrony Root Delay",
     "type": "timeseries",
     "description": "This is the total of the network path delays to the stratum-1 computer from which the computer is ultimately synchronized. Root delay values are printed in nanosecond resolution. In certain extreme situations, this value can be negative. (This can arise in a symmetric peer arrangement where the computers’ frequencies are not tracking each other and the network delay is very short relative to the turn-around time at each computer.)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "lambda_guest_agent_chrony_root_delay{host=~\"$host\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Chrony System Time",
     "type": "timeseries",
     "description": "In normal operation, chronyd never steps the system clock, because any jump in the timescale can have adverse consequences for certain application programs. Instead, any error in the system clock is corrected by slightly speeding up or slowing down the system clock until the error has been removed, and then returning to the system clock’s normal speed. A consequence of this is that there will be a period when the system clock (as read by other programs using the gettimeofday() system call, or by the date command in the shell) will be different from chronyd's estimate of the current true time (which it reports to NTP clients when it is operating in server mode). The value reported on this line is the difference due to this effect.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "lambda_guest_agent_chrony_system_time{host=~\"$host\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}