version: 1
project_name: lambda-guest-agent

builds:
  - id: default
    main: ./
    binary: lambda-guest-agent
    goos:
    - linux
    goarch:
    - arm64
    - amd64

nfpms:
  - id: default
    package_name: lambda-guest-agent
    vendor: Lambda Labs
    homepage: https://github.com/lambdal/guest-agent
    maintainer: Landon Clipp <landon@lambdal.com>
    description: Description
    formats: [deb]
    dependencies:
    - telegraf
    contents:
    - src: files/etc/lambda/guest-agent
      dst: /etc/lambda/guest-agent
      type: tree
    - src: files/etc/systemd/system/lambda-guest-agent.service.d
      dst: /etc/systemd/system/lambda-guest-agent.service.d
      type: tree
    scripts:
      preinstall: "scripts/preinstall.sh"
      postinstall: "scripts/postinstall.sh"

archives:
  - id: default
    format: tar.gz
    builds: [default]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: lambdal
    name: guest-agent
  ids:
  - default

publishers:
- name: artifactory-staging
  cmd: >-
    jfrog rt upload --deb focal/main/{{ .Arch }} "{{ .ArtifactName }}" "guest-agent/"
  dir: "{{ dir .ArtifactPath }}"


