version: "3"



dotenv: ["guest-agent.env"]

tasks:
  mkdir:
    requires: 
      vars: [DIR]
    cmds:
      - mkdir -p {{.DIR}}

  tag:
    desc: Tag the git repo with the version specified in the VERSION file.
    cmds:
    - git tag {{ .VERSION }}
    - git push origin {{ .VERSION }}
    vars:
      VERSION:
        sh: cat VERSION | head -n 1 | tr -d '\n'

  telegraf.clone:
    desc: Clone the telegraf repo at a specific tag
    deps:
    - task: mkdir
      vars:
        DIR: ./build
    cmds:
      - cd ./build && rm -rf telegraf/ && git clone --depth 1 --branch {{.TELEGRAF_VERSION}} https://github.com/influxdata/telegraf.git
    vars:
      TELEGRAF_VERSION:
        sh: head -n 1 ./TELEGRAF_VERSION | tr -d '\n'

  build.telegraf:
    desc: Build telegraf
    deps:
      - telegraf.clone
    cmds:
      - cd $GUEST_AGENT_TELEGRAF_BUILD_DIR && make build_tools
      - cd $GUEST_AGENT_TELEGRAF_BUILD_DIR && ./tools/custom_builder/custom_builder --config ../../build/files/$GUEST_AGENT_TELEGRAF_CONF
      - mkdir -p ./build/files/$GUEST_AGENT_LAMBDA_BIN_DIR
      - mv $GUEST_AGENT_TELEGRAF_BUILD_DIR/telegraf $GUEST_AGENT_TEMPLATES_OUTDIR/$GUEST_AGENT_LAMBDA_BIN_DIR/telegraf
    generates:
      - ./build/files/$GUEST_AGENT_LAMBDA_BIN_DIR/telegraf
    env:
      GOOS: linux
      GOARCH: amd64

  build.templates:
    desc: Render configuration templates
    cmds:
      - go run . render_template

  build.clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf ./build
      - rm -rf ./dist

  build:
    desc: Build only the binary artifacts.
    cmds:
      - goreleaser build
    deps:
      - build.clean
      - build.templates
      - build.telegraf
    requires:
      vars:
      - GITHUB_TOKEN

  release:
    desc: Build binaries, create .deb files, and upload/release the artifacts.
    deps: [build]
    cmds:
    - goreleaser release --clean
    requires:
      vars:
      - ARTIFACTORY_SECRET
      - GITHUB_TOKEN

  release.snapshot:
    desc: Build binaries, create .deb files. Ignore dirty git states.
    cmds:
    - goreleaser release --snapshot
    requires:
      vars:
      - GITHUB_TOKEN
