version: 1
project_name: lambda-guest-agent

builds:
  - id: guest-agent-amd64
    main: ./
    goos:
    - linux
    goarch: [amd64]
  - id: guest-agent-arm64
    main: ./
    goos:
    - linux
    goarch: [arm64]

nfpms:
  - &nfpm
    id: guest-agent-amd64
    builds: [guest-agent-amd64]
    package_name: lambda-guest-agent
    vendor: Lambda Labs
    homepage: https://github.com/lambdal/guest-agent
    maintainer: Landon Clipp <landon@lambdal.com>
    description: Description
    formats: [deb]
    contents:
    - src: ../build/files/etc/lambda/guest-agent/
      dst: /etc/lambda/guest-agent/
      type: tree
    - src: ../build/files/usr/local/bin/lambda/
      dst: /usr/local/bin/lambda/
      type: tree
    - src: ../build/files/usr/local/bin/telegraf-amd64
      dst: /usr/local/bin/lambda/telegraf
    scripts:
      preinstall: "../build/files/scripts/preinstall.sh"
      postinstall: "../build/files/scripts/postinstall.sh"
      preremove: "../build/files/scripts/preremove.sh"
      postremove: "../build/files/scripts/postremove.sh"
  - <<: *nfpm
    id: guest-agent-arm64
    builds: [guest-agent-arm64]
    contents:
    - src: ../build/files/etc/lambda/guest-agent/
      dst: /etc/lambda/guest-agent/
      type: tree
    - src: ../build/files/usr/local/bin/lambda/
      dst: /usr/local/bin/lambda/
      type: tree
    - src: ../build/files/usr/local/bin/telegraf-arm64
      dst: /usr/local/bin/lambda/telegraf

archives:
  - id: guest-agent
    format: tar.gz
    builds: [default]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: lambdal
    name: guest-agent
  ids:
  - default

publishers:
- name: artifactory
  cmd: >-
    jfrog rt upload --deb stable/main/{{ .Arch }} "{{ .ArtifactName }}" "guest-agent/"
  dir: "{{ dir .ArtifactPath }}"
