name: Promote package to prod

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to promote, without the leading 'v'."
        type: string
        required: true

run-name: "Promote v${{ github.event.inputs.version }} to prod | @${{ github.actor}}"

jobs:
  release-prod:
    runs-on: lambda-ubuntu-latest
    steps:
      - uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.ARTIFACTORY_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_API_TOKEN }}

      - name: Test Jfrog CLI connection
        run: jf rt ping

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x

      - name: Install deb-s3 dependencies
        run: sudo apt install wget

      - name: Setup deb-s3
        run: |
          sudo wget -O /etc/apt/trusted.gpg.d/deb-s3-archive-keyring.gpg https://raw.githubusercontent.com/deb-s3/deb-s3/master/deb-s3-archive-keyring.gpg
          echo "deb https://deb-s3-repo.s3.us-east-2.amazonaws.com/$(lsb_release -is | tr A-Z a-z)/ $(lsb_release -cs) main" | sudo tee -a /etc/apt/sources.list > /dev/null
          sudo apt update
          sudo apt install -y deb-s3
          sudo gem install deb-s3
      
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Release prod
        run: task release.prod
        env:
          GUEST_AGENT_VERSION: ${{ github.event.inputs.version }}

