name: Create new Git tag

on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  tag_and_push:
    runs-on: ubuntu-latest
    outputs:
      tag_exit_code: ${{ steps.tag.outputs.exitcode }}
    steps:
      - uses: actions/checkout@v2
        with:
          # We need entire history of tags
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
          check-latest: true
          cache-dependency-path: "**/*.sum"
      - name: Download Go dependencies
        run: go mod download

      - name: Run tagging commands
        id: tag
        run: |
          set +e
          go run github.com/go-task/task/v3/cmd/task tag
          exitcode="$?"
          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
          # The range between 8 and 63 inclusive is reserved for custom
          # error codes that contain specific meaning.
          if [ $exitcode -lt 8 -o $exitcode -gt 63 ]; then
            exit $exitcode
          fi
      - name: Push tags
        run: go run github.com/go-task/task/v3/cmd/task tag.push
        if: ${{ steps.tag.outputs.exitcode }} == 0

  release_staging:
    runs-on: ubuntu-latest
    needs: tag_and_push
    # Return code of 0 is returned only if a new tag was truly
    # pushed. Otherwise there is nothing to release.
    if: needs.tag_and_push.outputs.tag_exit_code == 0
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
          check-latest: true
          cache-dependency-path: "**/*.sum"

      - uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: ${{ vars.ARTIFACTORY_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_API_TOKEN }}

      - name: Test Jfrog CLI connection
        run: jf rt ping

      - name: Build and Release
        run: go run github.com/go-task/task/v3/cmd/task release.staging