name: Create new Git tag

on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # We need entire history of tags
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
          check-latest: true
          cache-dependency-path: "**/*.sum"
      - name: Download Go dependencies
        run: go mod download
      - name: Run tagging commands
        run: go run github.com/go-task/task/v3/cmd/task tag
      - name: Push tags
        run: go run github.com/go-task/task/v3/cmd/task tag.push

